<?php declare(strict_types=1);

namespace PayCal\Tests\Soc2;

use DateInterval;
use DateTimeImmutable;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * CC4 — Monitoring Alert-Proof Invariants
 *
 * Purpose:
 *   Verify retained alert-delivery proof evidence exists, is structurally
 *   valid, and remains fresh enough for monthly SOC2 evidence continuity.
 *
 * Why here:
 *   CC4 monitoring evidence should be continuously test-attested, not only
 *   generated by scripts.
 *
 * @internal
 */
#[Group('unit')]
#[Group('soc2')]
final class Cc4MonitoringAlertProofInvariantsTest extends TestCase
{
  private string $repoRoot;

  protected function setUp(): void
  {
    $this->repoRoot = dirname(__DIR__, 3);
  }

  /**
   * @return array<string, mixed>
   */
  private function readAlertProof(): array
  {
    $path = $this->repoRoot . '/soc2/reports/alert-delivery-proofs/proof-latest.json';
    $this->assertFileExists($path, 'Alert-delivery proof must exist for CC4 evidence.');

    $raw = file_get_contents($path);
    $this->assertIsString($raw);

    $data = json_decode($raw, true);
    $this->assertIsArray($data, 'Alert-delivery proof must be valid JSON.');
    return $data;
  }

  #[Test]
  public function alertProofHasRequiredFieldsAndProbeStructure(): void
  {
    $data = $this->readAlertProof();

    $this->assertSame('v1', $data['schema_version'] ?? null);
    $this->assertSame('alert-delivery-proof', $data['artifact_type'] ?? null);
    $this->assertIsArray($data['soc2_controls'] ?? null);
    $this->assertContains('CC4', $data['soc2_controls']);
    $this->assertContains('CC7', $data['soc2_controls']);

    $this->assertContains($data['conclusion'] ?? '', ['HEALTHY', 'DEGRADED']);

    $probes = $data['probes'] ?? null;
    $this->assertIsArray($probes);
    $this->assertGreaterThanOrEqual(4, count($probes), 'Alert proof must include expected probe coverage.');

    foreach ($probes as $i => $probe) {
      $this->assertIsArray($probe, "Probe {$i} must be an object.");
      $this->assertNotEmpty(trim((string) ($probe['endpoint'] ?? '')), "Probe {$i} endpoint is required.");
      $this->assertNotEmpty(trim((string) ($probe['url'] ?? '')), "Probe {$i} URL is required.");
      $this->assertContains(
        (string) ($probe['result'] ?? ''),
        ['OK', 'NON_200', 'CURL_ERROR'],
        "Probe {$i} result must be one of OK/NON_200/CURL_ERROR."
      );
    }
  }

  #[Test]
  public function alertProofIsFreshWithinThirtyFiveDays(): void
  {
    $data = $this->readAlertProof();

    $capturedAt = (string) ($data['captured_at_utc'] ?? '');
    $this->assertMatchesRegularExpression('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/', $capturedAt);

    $captured = DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s\Z', $capturedAt);
    $this->assertInstanceOf(DateTimeImmutable::class, $captured);

    $maxAge = new DateInterval('P35D');
    $cutoff = (new DateTimeImmutable('now'))->sub($maxAge);

    $this->assertGreaterThanOrEqual(
      $cutoff->getTimestamp(),
      $captured->getTimestamp(),
      'Alert proof is stale; run scripts/soc2-capture-alert-proof.sh --force and re-bundle evidence.'
    );
  }
}
