<?php declare(strict_types=1);

/**
 * system-limits-master.php
 *
 * Purpose: Define canonical system-limit defaults and limits metadata.
 *
 * PHP version 8.4.16
 *
 * LICENSE: Part of PayCal.app, licensed under a proprietary license.
 * Unauthorized copying, modification, distribution or use is prohibited.
 *
 * @category   Configuration
 * @package    PayCal
 * @author     Chris Simmons <cshaiku@gmail.com>
 * @copyright  2026 PayCal Technologies Inc.
 * @license    Proprietary License - See LICENSE.txt for full terms
 */

return [
    'pagination_max_per_page' => [
        'type' => 'int',
        'category' => 'pagination',
        'default' => 100,
        'min' => 10,
        'max' => 1000,
        'label' => 'Max Items Per Page',
        'help' => 'Maximum number of items displayed in paginated lists',
    ],
    'pagination_default_per_page' => [
        'type' => 'int',
        'category' => 'pagination',
        'default' => 50,
        'min' => 10,
        'max' => 500,
        'label' => 'Default Items Per Page',
        'help' => 'Default number of items per page',
    ],
    'max_user_sites' => [
        'type' => 'int',
        'category' => 'quotas',
        'default' => 100,
        'min' => 10,
        'max' => 1000,
        'label' => 'Max Sites Per User',
        'help' => 'Maximum number of sites a user can create',
    ],
    'min_character_length' => [
        'type' => 'int',
        'category' => 'quotas',
        'default' => 3,
        'min' => 1,
        'max' => 10,
        'label' => 'Min Character Length',
        'help' => 'Minimum character length for text inputs',
    ],
    'hash_length' => [
        'type' => 'int',
        'category' => 'quotas',
        'default' => 9,
        'min' => 6,
        'max' => 16,
        'label' => 'Hash Length',
        'help' => 'Length of generated hash identifiers',
    ],
    'year_min' => [
        'type' => 'int',
        'category' => 'quotas',
        'default' => 2020,
        'min' => 2000,
        'max' => 2050,
        'label' => 'Minimum Year',
        'help' => 'Earliest year allowed in the system',
    ],
    'year_max' => [
        'type' => 'int',
        'category' => 'quotas',
        'default' => 2100,
        'min' => 2050,
        'max' => 2150,
        'label' => 'Maximum Year',
        'help' => 'Latest year allowed in the system',
    ],
    'session_timeout_minutes' => [
        'type' => 'int',
        'category' => 'session',
        'default' => 1440,
        'min' => 30,
        'max' => 10080,
        'label' => 'Session Timeout (min)',
        'help' => 'User session timeout (30 min - 7 days)',
    ],
    'cookie_expiry_days' => [
        'type' => 'int',
        'category' => 'session',
        'default' => 30,
        'min' => 1,
        'max' => 365,
        'label' => 'Cookie Expiry (d)',
        'help' => 'Cookie expiration time in days',
    ],
    'new_session_ttl_days' => [
        'type' => 'int',
        'category' => 'session',
        'default' => 30,
        'min' => 1,
        'max' => 90,
        'label' => 'New Session TTL (d)',
        'help' => 'Time-to-live for new sessions in Redis',
    ],
    'new_user_ttl_hours' => [
        'type' => 'int',
        'category' => 'session',
        'default' => 1,
        'min' => 1,
        'max' => 48,
        'label' => 'New User TTL (h)',
        'help' => 'Time-to-live for new user data in Redis',
    ],
    'default_pay_period_length' => [
        'type' => 'int',
        'category' => 'work',
        'default' => 14,
        'min' => 7,
        'max' => 31,
        'label' => 'Default Pay Period (d)',
        'help' => 'Default pay period length in days',
    ],
    'default_work_week_length' => [
        'type' => 'int',
        'category' => 'work',
        'default' => 7,
        'min' => 5,
        'max' => 7,
        'label' => 'Work Week Length (d)',
        'help' => 'Number of days in a work week',
    ],
    'max_daily_regular_hours' => [
        'type' => 'int',
        'category' => 'work',
        'default' => 8,
        'min' => 6,
        'max' => 12,
        'label' => 'Max Daily Regular Hours',
        'help' => 'Maximum regular hours before overtime',
    ],
    'max_weekly_regular_hours' => [
        'type' => 'int',
        'category' => 'work',
        'default' => 44,
        'min' => 35,
        'max' => 60,
        'label' => 'Max Weekly Regular Hours',
        'help' => 'Maximum weekly hours before overtime',
    ],
    'pay_overtime_scale' => [
        'type' => 'float',
        'category' => 'work',
        'default' => 1.5,
        'min' => 1.0,
        'max' => 3.0,
        'label' => 'Overtime Pay Scale',
        'help' => 'Multiplier for overtime pay (e.g., 1.5 = time-and-a-half)',
    ],
    'max_daily_hours_absolute' => [
        'type' => 'int',
        'category' => 'work',
        'default' => 24,
        'min' => 16,
        'max' => 24,
        'label' => 'Max Daily Hours (absolute)',
        'help' => 'Hard limit on hours per day',
    ],
    'min_daily_hours' => [
        'type' => 'float',
        'category' => 'work',
        'default' => 0.0,
        'min' => 0.0,
        'max' => 8.0,
        'label' => 'Min Daily Hours',
        'help' => 'Minimum hours that can be logged per day',
    ],
    'redis_scan_batch_size' => [
        'type' => 'int',
        'category' => 'database',
        'default' => 100,
        'min' => 10,
        'max' => 1000,
        'label' => 'Redis Scan Batch Size',
        'help' => 'Number of keys per Redis SCAN operation',
    ],
    'redis_connect_timeout' => [
        'type' => 'float',
        'category' => 'database',
        'default' => 2.5,
        'min' => 1.0,
        'max' => 10.0,
        'label' => 'Redis Connect Timeout (s)',
        'help' => 'Redis connection timeout in seconds',
    ],
    'enable_debug_logging' => [
        'type' => 'bool',
        'category' => 'features',
        'default' => false,
        'label' => 'Enable Debug Logging',
        'help' => 'Enable verbose debug logging (may impact performance)',
    ],
    'enable_rate_limiting' => [
        'type' => 'bool',
        'category' => 'features',
        'default' => true,
        'label' => 'Enable Rate Limiting',
        'help' => 'Enable API rate limiting for security',
    ],
    'account_recovery_enabled' => [
        'type' => 'bool',
        'category' => 'account_security',
        'default' => true,
        'label' => 'Enable Account Recovery',
        'help' => 'Enable emailed Recovery Key based account recovery flow',
    ],
    'account_recovery_auto_block_enabled' => [
        'type' => 'bool',
        'category' => 'account_security',
        'default' => true,
        'label' => 'Enable Account Recovery Auto Block',
        'help' => 'Automatically block obvious recovery replay abuse by hashed IP',
    ],
    'account_recovery_code_ttl_minutes' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 15,
        'min' => 5,
        'max' => 60,
        'label' => 'Account Recovery Code TTL (min)',
        'help' => 'Expiration time for recovery email codes',
    ],
    'account_recovery_resend_cooldown_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 60,
        'min' => 30,
        'max' => 300,
        'label' => 'Account Recovery Resend Cooldown (s)',
        'help' => 'Minimum delay between recovery code resend attempts',
    ],
    'account_recovery_max_resends_per_hour' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 5,
        'min' => 1,
        'max' => 20,
        'label' => 'Account Recovery Max Resends Per Hour',
        'help' => 'Maximum recovery code resend attempts allowed per hour',
    ],
    'account_recovery_max_verify_attempts' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 5,
        'min' => 1,
        'max' => 20,
        'label' => 'Account Recovery Max Verify Attempts',
        'help' => 'Maximum email or proof verification failures per transaction',
    ],
    'account_recovery_max_starts_per_day' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 5,
        'min' => 1,
        'max' => 25,
        'label' => 'Account Recovery Max Starts Per Day',
        'help' => 'Maximum number of recovery starts allowed per day',
    ],
    'account_recovery_txn_ttl_minutes' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 30,
        'min' => 10,
        'max' => 120,
        'label' => 'Account Recovery Transaction TTL (min)',
        'help' => 'Expiration time for recovery transactions',
    ],
    'account_recovery_proof_nonce_ttl_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 180,
        'min' => 30,
        'max' => 600,
        'label' => 'Account Recovery Proof Nonce TTL (s)',
        'help' => 'Expiration time for recovery proof nonce challenges',
    ],
    'account_recovery_bootstrap_ttl_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 300,
        'min' => 30,
        'max' => 900,
        'label' => 'Account Recovery Bootstrap TTL (s)',
        'help' => 'How long recovery bootstrap may be used to register a replacement passkey',
    ],
    'account_recovery_supersede_cooldown_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 60,
        'min' => 30,
        'max' => 300,
        'label' => 'Account Recovery Supersede Cooldown (s)',
        'help' => 'Minimum delay before a new recovery start may supersede an active transaction',
    ],
    'account_recovery_replay_block_threshold' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 50,
        'min' => 5,
        'max' => 500,
        'label' => 'Account Recovery Replay Block Threshold',
        'help' => 'Replay events from one hashed IP required before automatic blocking',
    ],
    'account_recovery_replay_block_window_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 900,
        'min' => 60,
        'max' => 3600,
        'label' => 'Account Recovery Replay Block Window (s)',
        'help' => 'Time window used to count replay attempts for automatic blocking',
    ],
    'account_recovery_replay_ip_block_ttl_minutes' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 60,
        'min' => 5,
        'max' => 1440,
        'label' => 'Account Recovery Replay IP Block TTL (min)',
        'help' => 'Duration of hashed IP blocks applied after replay abuse',
    ],
    'recovery_email_required_for_email_change' => [
        'type' => 'bool',
        'category' => 'account_security',
        'default' => true,
        'label' => 'Require Recovery Email For Email Change',
        'help' => 'Block primary email changes until a verified recovery email exists',
    ],
    'email_change_stepup_max_age_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 300,
        'min' => 60,
        'max' => 3600,
        'label' => 'Email Change Step-Up Max Age (s)',
        'help' => 'Maximum age of passkey step-up assertion before starting email change',
    ],
    'email_change_code_ttl_minutes' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 15,
        'min' => 5,
        'max' => 60,
        'label' => 'Email Change Code TTL (min)',
        'help' => 'Expiration time for old/new email verification codes',
    ],
    'email_change_resend_cooldown_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 60,
        'min' => 30,
        'max' => 300,
        'label' => 'Email Change Resend Cooldown (s)',
        'help' => 'Minimum seconds between resend-code actions for email change',
    ],
    'email_change_max_resends_per_hour' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 5,
        'min' => 1,
        'max' => 20,
        'label' => 'Email Change Max Resends Per Hour',
        'help' => 'Maximum code resend attempts per user per hour for email change',
    ],
    'email_change_max_verify_attempts' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 8,
        'min' => 3,
        'max' => 20,
        'label' => 'Email Change Max Verify Attempts',
        'help' => 'Maximum combined code verification attempts before email change lockout',
    ],
    'email_change_max_new_email_starts_per_day' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 10,
        'min' => 1,
        'max' => 50,
        'label' => 'Email Change Max Starts Per Day',
        'help' => 'Maximum number of new email-change transactions started per user per day',
    ],
    'recovery_email_code_ttl_minutes' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 15,
        'min' => 5,
        'max' => 60,
        'label' => 'Recovery Email Code TTL (min)',
        'help' => 'Expiration time for recovery-email verification codes',
    ],
    'recovery_email_resend_cooldown_seconds' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 60,
        'min' => 30,
        'max' => 300,
        'label' => 'Recovery Email Resend Cooldown (s)',
        'help' => 'Minimum seconds between recovery-email code resend actions',
    ],
    'recovery_email_max_resends_per_hour' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 5,
        'min' => 1,
        'max' => 20,
        'label' => 'Recovery Email Max Resends Per Hour',
        'help' => 'Maximum recovery-email code resend attempts per user per hour',
    ],
    'recovery_email_max_verify_attempts' => [
        'type' => 'int',
        'category' => 'account_security',
        'default' => 8,
        'min' => 3,
        'max' => 20,
        'label' => 'Recovery Email Max Verify Attempts',
        'help' => 'Maximum recovery-email code verification attempts before lockout',
    ],
    'text_size_smaller' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '50%',
        'label' => 'Text Size: Smaller',
        'help' => 'Font size for "smaller" text setting (CSS percentage)',
    ],
    'text_size_base' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '62.5%',
        'label' => 'Text Size: Base',
        'help' => 'Base font size (CSS percentage)',
    ],
    'text_size_larger' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '125%',
        'label' => 'Text Size: Larger',
        'help' => 'Font size for "larger" text setting (CSS percentage)',
    ],
    'line_height_less' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '1.5rem',
        'label' => 'Line Height: Less',
        'help' => 'Reduced line height (CSS rem value)',
    ],
    'line_height_more' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '2.0rem',
        'label' => 'Line Height: More',
        'help' => 'Increased line height (CSS rem value)',
    ],
    'spacing_less' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '1.00rem',
        'label' => 'Spacing: Less',
        'help' => 'Reduced spacing (CSS rem value)',
    ],
    'spacing_more' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => '1.20rem',
        'label' => 'Spacing: More',
        'help' => 'Increased spacing (CSS rem value)',
    ],
    'font_size_adjustment_override_px' => [
        'type' => 'int',
        'category' => 'ui',
        'default' => 0,
        'min' => -5,
        'max' => 5,
        'label' => 'Font Size Adjustment Override (px)',
        'help' => 'Global pixel adjustment applied on top of user text slider values',
    ],
    'spacing_adjustment_override_rem' => [
        'type' => 'int',
        'category' => 'ui',
        'default' => 0,
        'min' => -5,
        'max' => 5,
        'label' => 'Spacing Adjustment Override (rem)',
        'help' => 'Global rem adjustment applied on top of user spacing slider values',
    ],
    'default_theme' => [
        'type' => 'string',
        'category' => 'ui',
        'default' => 'dark',
        'options' => ['dark', 'light'],
        'label' => 'Default Theme',
        'help' => 'Default color theme for new users',
    ],
];
