/var/www/paycal/logs/contact-email.log {
    daily
    rotate 3650
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    dateext
    dateformat -%Y%m%d
    su www-data www-data
    create 0640 www-data www-data
}
