<?php
/**
 * Public Transparency: Accessibility
 *
 * PURPOSE: Document accessibility features, intent, and implementation priorities.
 */

declare(strict_types=1);

require_once __DIR__ . '/../../config.php';

$i18n = [];
$i18nKeys = [
  'BREADCRUMB',
  'HELP_TOC_TRANSPARENCY_HUB',
  'TRANSPARENCY_ACCESSIBILITY_PAGE_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_DECK',
  'TRANSPARENCY_ACCESSIBILITY_WHY_PAGE_EXISTS_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_WHY_PAGE_EXISTS_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_WHY_PAGE_EXISTS_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_WORKING_STANDARD_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_WORKING_STANDARD_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_WORKING_STANDARD_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_ROUTE_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_LAST_VERIFIED_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_NEXT_REVIEW_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_SCOPE_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_FACT_1',
  'TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_FACT_2',
  'TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_FACT_3',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_POLICY_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_PLATFORM',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_BROWSER',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_ASSISTIVE_TECH',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_SUPPORT_EXPECTATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_VERIFICATION_MODEL',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_PLATFORM',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_BROWSER',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_AT',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_EXPECTATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_VERIFICATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_PLATFORM',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_BROWSER',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_AT',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_EXPECTATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_VERIFICATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_PLATFORM',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_BROWSER',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_AT',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_EXPECTATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_VERIFICATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_PLATFORM',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_BROWSER',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_AT',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_EXPECTATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_VERIFICATION',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_POLICY_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_FACT_1',
  'TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_FACT_2',
  'TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_FACT_3',
  'TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_REVIEW_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_REVIEW_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_DEPENDENCY',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_USAGE',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_STATUS',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_NOTES',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_APPROVED',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_CONDITIONAL',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_BLOCKED',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_REVIEW_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_1',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_2',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_3',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_4',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_5',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_6',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_7',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_8',
  'TRANSPARENCY_ACCESSIBILITY_IN_PLACE_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_QUICK_KEYS_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_QUICK_KEYS_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_QUICK_KEYS_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_FOCUS_SAFETY_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_FOCUS_SAFETY_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_1',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_2',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_3',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_1',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_2',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_3',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_4',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_5',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_6',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_7',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_8',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_9',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_10',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_11',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_12',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_13',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_14',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_4',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_5',
  'TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_STILL_IMPROVING_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_STILL_IMPROVING_FACT_1',
  'TRANSPARENCY_ACCESSIBILITY_OPEN_WORK_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_OPEN_WORK_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_AUDIT_CADENCE_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_CAPTION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_SEVERITY',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_DEFINITION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_ACKNOWLEDGE',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_FIX_TARGET',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_OWNER',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_ESCALATION_PATH',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_DEFINITION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_ESCALATION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_ACKNOWLEDGE',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_FIX_TARGET',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_OWNER',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_SEVERITY',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_DEFINITION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_ACKNOWLEDGE',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_FIX_TARGET',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_OWNER',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_ESCALATION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_SEVERITY',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_DEFINITION',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_ACKNOWLEDGE',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_FIX_TARGET',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_OWNER',
  'TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_ESCALATION',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_KEYBOARD_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_CLEAR_STRUCTURE_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_READABLE_PRESENTATION_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_SAFE_NAVIGATION_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_DIRECT_FEEDBACK_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_KEYBOARD_TEXT',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_CLEAR_STRUCTURE_TEXT',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_READABLE_PRESENTATION_TEXT',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_SAFE_NAVIGATION_TEXT',
  'TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_DIRECT_FEEDBACK_TEXT',
  'TRANSPARENCY_ACCESSIBILITY_ROUTE_METADATA_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_FOCUS_SAFETY_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_HOW_USE_ARIA_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_HOW_USE_ARIA_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_HOW_USE_ARIA_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_LABEL_SUMMARY',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_LABEL_DETAILS',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_PLACEHOLDER_SUMMARY',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_PLACEHOLDER_DETAILS',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_FORM_HELP',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_BUTTON_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_HELPFUL_DETAILS_LABEL',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_1',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_2',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_3',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_4',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_1',
  'TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_2',
  'TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_3',
  'TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_4',
  'TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_CONTINUOUS_PRACTICE_TITLE',
  'TRANSPARENCY_ACCESSIBILITY_CONTINUOUS_PRACTICE_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_CONTINUOUS_PRACTICE_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_SUPPORT_POLICY_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_PDFLIB_USAGE',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_PDFLIB_STATUS',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_PDFLIB_NOTES',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_TWEETNACL_USAGE',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_TWEETNACL_STATUS',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_TWEETNACL_NOTES',
  'TRANSPARENCY_ACCESSIBILITY_AUDIT_CADENCE_TEXT_1',
  'TRANSPARENCY_ACCESSIBILITY_AUDIT_CADENCE_TEXT_2',
  'TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_SCOPE_VALUE',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_APPROVED_DESC',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_CONDITIONAL_DESC',
  'TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_BLOCKED_DESC',
  'TRANSPARENCY_ACCESSIBILITY_OPEN_WORK_WCAG026_TEXT',
];
foreach ($i18nKeys as $key) {
  $i18n[$key] = \PayCal\Domain\Strings::i18n($key);
}

$currentPage = 'PAGE_TRANSPARENCY';
$pageTitle = $i18n['TRANSPARENCY_ACCESSIBILITY_PAGE_TITLE'] . ' - [PayCal]';
$pageLabel = $i18n['TRANSPARENCY_ACCESSIBILITY_PAGE_TITLE'];
require_once HTML.'/header.php';
?>
<article class="article doc-article">
  <nav class="doc-breadcrumb" aria-label="<?php echo $i18n['BREADCRUMB']; ?>">
    <a href="<?php echo transparency_href('/transparency/'); ?>"><?php echo $i18n['HELP_TOC_TRANSPARENCY_HUB']; ?></a>
    <span class="separator">/</span>
    <span class="current"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_PAGE_TITLE']; ?></span>
  </nav>

  <header class="doc-article-header">
    <h1><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_PAGE_TITLE']; ?></h1>
    <p class="deck"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DECK']; ?></p>
    <p class="doc-article-meta">Published: <time datetime="2026-03-20">2026-03-20</time></p>
  </header>

  <div class="doc-article-body">
    <section class="doc-section highlight">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_WHY_PAGE_EXISTS_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_WHY_PAGE_EXISTS_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_WHY_PAGE_EXISTS_TEXT_2']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_WORKING_STANDARD_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_WORKING_STANDARD_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_WORKING_STANDARD_TEXT_2']; ?></p>
    </section>

    <section class="doc-section highlight">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_TITLE']; ?></h2>
      <div class="doc-two-column">
        <div>
          <h3><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ROUTE_METADATA_TITLE']; ?></h3>
          <ul class="doc-fact-list">
            <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_ROUTE_LABEL']; ?>:</strong> <code>/transparency/accessibility/</code></li>
            <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_LAST_VERIFIED_LABEL']; ?>:</strong> <time datetime="2026-04-12">2026-04-12</time></li>
            <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_NEXT_REVIEW_LABEL']; ?>:</strong> <time datetime="2026-06-23">2026-06-23</time></li>
            <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_SCOPE_LABEL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_SCOPE_VALUE']; ?></li>
          </ul>
        </div>
        <div>
          <h3><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_TITLE']; ?></h3>
          <ul class="doc-fact-list">
            <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_FACT_1']; ?></li>
            <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_FACT_2']; ?></li>
            <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KNOWN_LIMITATIONS_FACT_3']; ?></li>
          </ul>
        </div>
      </div>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_VERIFICATION_METADATA_TEXT_1']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_POLICY_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_POLICY_TEXT_1']; ?></p>
      <table class="doc-table">
        <thead>
          <tr>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_PLATFORM']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_BROWSER']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_ASSISTIVE_TECH']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_SUPPORT_EXPECTATION']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_TABLE_VERIFICATION_MODEL']; ?></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_PLATFORM']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_BROWSER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_AT']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_EXPECTATION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_MACOS_VERIFICATION']; ?></td>
          </tr>
          <tr>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_PLATFORM']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_BROWSER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_AT']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_EXPECTATION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_FIREFOX_VERIFICATION']; ?></td>
          </tr>
          <tr>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_PLATFORM']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_BROWSER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_AT']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_EXPECTATION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_WINDOWS_CHROME_VERIFICATION']; ?></td>
          </tr>
          <tr>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_PLATFORM']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_BROWSER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_AT']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_EXPECTATION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_ROW_OTHER_VERIFICATION']; ?></td>
          </tr>
        </tbody>
      </table>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_SUPPORT_POLICY_TEXT_2']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_FACT_1']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_FACT_2']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_FACT_3']; ?></li>
      </ul>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEPRECATION_POLICY_TEXT_1']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_REVIEW_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_REVIEW_TEXT_1']; ?></p>
      <table class="doc-table">
        <thead>
          <tr>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_DEPENDENCY']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_USAGE']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_STATUS']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_TABLE_NOTES']; ?></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><code>pdf-lib</code></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_PDFLIB_USAGE']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_PDFLIB_STATUS']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_PDFLIB_NOTES']; ?></td>
          </tr>
          <tr>
            <td><code>tweetnacl</code></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_TWEETNACL_USAGE']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_TWEETNACL_STATUS']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_ROW_TWEETNACL_NOTES']; ?></td>
          </tr>
        </tbody>
      </table>
      <ul class="doc-fact-list">
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_APPROVED']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_APPROVED_DESC']; ?></li>
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_CONDITIONAL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_CONDITIONAL_DESC']; ?></li>
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_BLOCKED']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_STATUS_BLOCKED_DESC']; ?></li>
      </ul>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_THIRD_PARTY_REVIEW_TEXT_2']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_1']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_2']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_3']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_4']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_5']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_6']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_7']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_FACT_8']; ?></li>
      </ul>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_IN_PLACE_TEXT_1']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_QUICK_KEYS_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_QUICK_KEYS_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_QUICK_KEYS_TEXT_2']; ?></p>

      <h3><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_FOCUS_SAFETY_TITLE']; ?></h3>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_FOCUS_SAFETY_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_FOCUS_SAFETY_TEXT_2']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_1']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_2']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_3']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_4']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_FACT_5']; ?></li>
      </ul>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_ACTIVELY_VERIFY_TEXT_1']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_1']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_2']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_3']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_4']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_5']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_6']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_7']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_8']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_9']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_10']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_11']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_12']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_13']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_RECENT_IMPROVEMENTS_ITEM_14']; ?></li>
      </ul>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STILL_IMPROVING_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STILL_IMPROVING_FACT_1']; ?></li>
      </ul>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_OPEN_WORK_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><strong>WCAG-026:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_OPEN_WORK_WCAG026_TEXT']; ?></li>
      </ul>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_OPEN_WORK_TEXT_1']; ?></p>
    </section>

    <section class="doc-section highlight">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_AUDIT_CADENCE_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_AUDIT_CADENCE_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_AUDIT_CADENCE_TEXT_2']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TEXT_1']; ?></p>
      <table class="doc-table">
        <caption class="visually_hidden"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_CAPTION']; ?></caption>
        <thead>
          <tr>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_SEVERITY']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_DEFINITION']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_ACKNOWLEDGE']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_FIX_TARGET']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_OWNER']; ?></th>
            <th scope="col"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_TABLE_ESCALATION_PATH']; ?></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>P0</strong></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_DEFINITION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_ACKNOWLEDGE']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_FIX_TARGET']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_OWNER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P0_ESCALATION']; ?></td>
          </tr>
          <tr>
            <td><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_SEVERITY']; ?></strong></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_DEFINITION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_ACKNOWLEDGE']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_FIX_TARGET']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_OWNER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P1_ESCALATION']; ?></td>
          </tr>
          <tr>
            <td><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_SEVERITY']; ?></strong></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_DEFINITION']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_ACKNOWLEDGE']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_FIX_TARGET']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_OWNER']; ?></td>
            <td><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_DEFECT_RESPONSE_P2_ESCALATION']; ?></td>
          </tr>
        </tbody>
      </table>
    </section>

    <section class="doc-section highlight">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_TITLE']; ?></h2>
      <ul class="doc-fact-list">
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_KEYBOARD_LABEL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_KEYBOARD_TEXT']; ?></li>
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_CLEAR_STRUCTURE_LABEL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_CLEAR_STRUCTURE_TEXT']; ?></li>
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_READABLE_PRESENTATION_LABEL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_READABLE_PRESENTATION_TEXT']; ?></li>
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_SAFE_NAVIGATION_LABEL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_SAFE_NAVIGATION_TEXT']; ?></li>
        <li><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_DIRECT_FEEDBACK_LABEL']; ?>:</strong> <?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_KEY_EXPECTATIONS_DIRECT_FEEDBACK_TEXT']; ?></li>
      </ul>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_HOW_USE_ARIA_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_HOW_USE_ARIA_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_HOW_USE_ARIA_TEXT_2']; ?></p>
    </section>

    <section class="doc-section success">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_TEXT_1']; ?></p>
      <form class="a11y-feedback-form" method="get" action="/contact/" aria-describedby="a11y_feedback_form_help">
        <input type="hidden" name="reason" value="bug">

        <label for="a11y_feedback_subject"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_LABEL_SUMMARY']; ?></label>
        <input id="a11y_feedback_subject" name="subject" type="text" maxlength="180" required placeholder="<?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_PLACEHOLDER_SUMMARY']; ?>">

        <label for="a11y_feedback_message"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_LABEL_DETAILS']; ?></label>
        <textarea id="a11y_feedback_message" name="message" rows="6" maxlength="6000" required placeholder="<?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_PLACEHOLDER_DETAILS']; ?>"></textarea>

        <p id="a11y_feedback_form_help" class="form-hint"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_FORM_HELP']; ?></p>
        <button type="submit" class="btn btn_primary"><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_BUTTON_LABEL']; ?></button>
      </form>
      <p><strong><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_HELPFUL_DETAILS_LABEL']; ?>:</strong></p>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_1']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_2']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_3']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_DETAIL_ITEM_4']; ?></li>
      </ul>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_REPORT_ISSUES_TEXT_2']; ?></p>
    </section>

    <section class="doc-section">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_TEXT_1']; ?></p>
      <ul class="doc-fact-list">
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_1']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_2']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_3']; ?></li>
        <li><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_STANDARDS_GUIDELINES_ITEM_4']; ?></li>
      </ul>
    </section>

    <section class="doc-section highlight">
      <h2><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_CONTINUOUS_PRACTICE_TITLE']; ?></h2>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_CONTINUOUS_PRACTICE_TEXT_1']; ?></p>
      <p><?php echo $i18n['TRANSPARENCY_ACCESSIBILITY_CONTINUOUS_PRACTICE_TEXT_2']; ?></p>
    </section>
  </div>
</article>
<?php
require_once HTML.'/footer.php';
